
create table "public"."chat" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null default auth.uid(),
    "title" text,
    "model" character varying default ''::character varying,
    "ts" timestamp without time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone
);


alter table "public"."chat" enable row level security ;


create table "public"."chat_message" (
"id" bigint generated by default as identity not null,
"chat_id" uuid not null,
"role" character varying not null,
"content" json not null,
"order" bigint generated by default as identity not null,
"ts" timestamp without time zone not null,
"created_at" timestamp with time zone not null default now ()
) ;


alter table "public"."chat_message" enable row level security ;

CREATE UNIQUE INDEX chat_message_pkey ON public.chat_message USING btree (id) ;

CREATE UNIQUE INDEX chat_pkey ON public.chat USING btree (id) ;

alter table "public"."chat" add constraint "chat_pkey" PRIMARY KEY using index "chat_pkey" ;

alter table "public"."chat_message" add constraint "chat_message_pkey" PRIMARY KEY using index "chat_message_pkey" ;

alter table "public"."chat" add constraint "chat_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE not valid ;

alter table "public"."chat" validate constraint "chat_user_id_fkey" ;

alter table "public"."chat_message" add constraint "chat_message_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES chat (id) ON UPDATE CASCADE ON DELETE CASCADE not valid ;

alter table "public"."chat_message" validate constraint "chat_message_chat_id_fkey" ;

grant delete on table "public"."chat" to "anon" ;

grant insert on table "public"."chat" to "anon" ;

grant references on table "public"."chat" to "anon" ;

grant select on table "public"."chat" to "anon" ;

grant trigger on table "public"."chat" to "anon" ;

grant truncate on table "public"."chat" to "anon" ;

grant update on table "public"."chat" to "anon" ;

grant delete on table "public"."chat" to "authenticated" ;

grant insert on table "public"."chat" to "authenticated" ;

grant references on table "public"."chat" to "authenticated" ;

grant select on table "public"."chat" to "authenticated" ;

grant trigger on table "public"."chat" to "authenticated" ;

grant truncate on table "public"."chat" to "authenticated" ;

grant update on table "public"."chat" to "authenticated" ;

grant delete on table "public"."chat" to "service_role" ;

grant insert on table "public"."chat" to "service_role" ;

grant references on table "public"."chat" to "service_role" ;

grant select on table "public"."chat" to "service_role" ;

grant trigger on table "public"."chat" to "service_role" ;

grant truncate on table "public"."chat" to "service_role" ;

grant update on table "public"."chat" to "service_role" ;

grant delete on table "public"."chat_message" to "anon" ;

grant insert on table "public"."chat_message" to "anon" ;

grant references on table "public"."chat_message" to "anon" ;

grant select on table "public"."chat_message" to "anon" ;

grant trigger on table "public"."chat_message" to "anon" ;

grant truncate on table "public"."chat_message" to "anon" ;

grant update on table "public"."chat_message" to "anon" ;

grant delete on table "public"."chat_message" to "authenticated" ;

grant insert on table "public"."chat_message" to "authenticated" ;

grant references on table "public"."chat_message" to "authenticated" ;

grant select on table "public"."chat_message" to "authenticated" ;

grant trigger on table "public"."chat_message" to "authenticated" ;

grant truncate on table "public"."chat_message" to "authenticated" ;

grant update on table "public"."chat_message" to "authenticated" ;

grant delete on table "public"."chat_message" to "service_role" ;

grant insert on table "public"."chat_message" to "service_role" ;

grant references on table "public"."chat_message" to "service_role" ;

grant select on table "public"."chat_message" to "service_role" ;

grant trigger on table "public"."chat_message" to "service_role" ;

grant truncate on table "public"."chat_message" to "service_role" ;

grant update on table "public"."chat_message" to "service_role" ;
